version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build-and-push-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t chunglm/reverseproxy:v1 udagram-reverseproxy
            docker build -t chunglm/udagram-api-user:v1 udagram-api-user
            docker build -t chunglm/udagram-api-feed:v2 udagram-api-feed
            docker build -t chunglm/udagram-frontend:v2 udagram-frontend
      - run:
          name: Push Docker image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push chunglm/reverseproxy:v1
            docker push chunglm/udagram-api-user:v1
            docker push chunglm/udagram-api-feed:v2
            docker push chunglm/udagram-frontend:v2

workflows:
  default:
    jobs:
      - build-and-push-image
