version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build-and-push-image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t chunglm/reverseproxy udagram-reverseproxy
            docker build -t chunglm/udagram-api-user udagram-api-user
            docker build -t chunglm/udagram-api-feed udagram-api-feed
            docker build -t chunglm/udagram-frontend udagram-frontend
      - run:
          name: Push Docker image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            docker push chunglm/reverseproxy
            docker push chunglm/udagram-api-user
            docker push chunglm/udagram-api-feed
            docker push chunglm/udagram-frontend

workflows:
  default:
    jobs:
      - build-and-push-image
