apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: chunglm/udagram-api-feed:v2
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
