apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  labels:
    app: frontend-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: frontend-loadbalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80